sudo: required # super user permissions needed to run any docker commands
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t hemakshis/udemy-docker-react .

script:
  - docker run --name test-udemy-docker-react-app hemakshis/udemy-docker-react npm run test -- --coverage