FROM node:alpine

WORKDIR /usr/app

COPY ./package.json ./
RUN npm install

# We can skip this COPY if we are using volumes, 
# but good to keep it for future references (reminder)
COPY . .

CMD ["npm", "run", "start"]
EXPOSE 3000