version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app # means map current folder "." (which is outside the container) to folder /usr/app (which is inside the container)
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["npm", "run", "test"]